version: 2.1

jobs:
  build-and-push-feed:         
    docker:    
      - image: cimg/base:current
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: echo "No need to install anything. \n Just build and push the Docker image."
      - run:
          name: Build and push Docker image api feed
          command: |
            echo "Inside the Build and push Docker image step"
            docker --version # print the version for logging
            cd udagram-api-feed
            docker build -t thinhota/udagram-api-feed .        
            docker tag thinhota/udagram-api-feed thinhota/udagram-api-feed:lastest
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push thinhota/udagram-api-feed:lastest

  build-and-push-user:
    docker:    
      - image: cimg/base:current
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: echo "No need to install anything. \n Just build and push the Docker image."
      - run:
          name: Build and push Docker image api user
          command: |
            echo "Inside the Build and push Docker image step"
            docker --version # print the version for logging
            cd udagram-api-user
            docker build -t thinhota/udagram-api-user .        
            docker tag thinhota/udagram-api-user thinhota/udagram-api-user:lastest
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push thinhota/udagram-api-user:lastest

  build-and-push-front-end:
    docker:    
      - image: cimg/base:current
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: echo "No need to install anything. \n Just build and push the Docker image."
      - run:
          name: Build and push Docker image front end
          command: |
            echo "Inside the Build and push Docker image step"
            docker --version # print the version for logging
            cd udagram-frontend
            docker build -t thinhota/udagram-frontend .        
            docker tag thinhota/udagram-frontend thinhota/udagram-frontend:lastest
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push thinhota/udagram-frontend:lastest

  build-and-push-reverseproxy:
    docker:    
      - image: cimg/base:current
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: echo "No need to install anything. \n Just build and push the Docker image."
      - run:
          name: Build and push Docker image reverse proxy
          command: |
            echo "Inside the Build and push Docker image step"
            docker --version # print the version for logging
            cd udagram-reverseproxy
            docker build -t thinhota/reverseproxy .        
            docker tag thinhota/reverseproxy thinhota/reverseproxy:lastest
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push thinhota/reverseproxy:lastest

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-push-feed
      - build-and-push-user
      - build-and-push-front-end
      - build-and-push-reverseproxy